FROM xebialabs/xl-release:8.5.0

# Add license file
COPY default-conf/* /opt/xebialabs/xl-release-server/default-conf/

# Add latest DevOps as Code build
# COPY lib/* /opt/xebialabs/xl-release-server/lib/
