#!/usr/bin/env bash
echo "Security group id:"
SGID=$(aws ec2 describe-security-groups --filter "Name=group-name,Values=`whoami`-ror-ecs-security-group" --output text --query 'SecurityGroups[0].GroupId')
echo "          - $SGID"

echo "Subnet ids:"
SUBNETIDA=$(aws ec2 describe-subnets --filter "Name=tag:Name,Values=`whoami`-ror-ecs-subnet-ipv4-az-1a" --output text --query 'Subnets[0].SubnetId')
echo "          - $SUBNETIDA"
SUBNETIDB=$(aws ec2 describe-subnets --filter "Name=tag:Name,Values=`whoami`-ror-ecs-subnet-ipv4-az-1b" --output text --query 'Subnets[0].SubnetId')
echo "          - $SUBNETIDB"
