#!/usr/bin/env bash
SGID=$(aws ec2 describe-security-groups --filter "Name=group-name,Values=`whoami`-ror-ecs-security-group" --output text --query 'SecurityGroups[0].GroupId')
PUBIP=$(aws ec2 describe-network-interfaces --filter="Name=group-id,Values=$SGID" --output text --query 'NetworkInterfaces[0].Association.PublicIp')
echo "Access rest-o-rant-web at http://$PUBIP"
echo "Access rest-o-rant-api at http://$PUBIP:8080/rest-o-rant-api/findrestaurants"

# The open command only works on macOS
if [ `uname -s` == "Darwin" ]; then
  open "http://$PUBIP"
fi
